############################
### LOCALHOST ###
############################

GET http://localhost:8080/friends
###
GET http://localhost:8080/friends/62916a85aba29cb39935f616
###
POST http://localhost:8080/friends HTTP/1.1 
content-type: application/json

{
    "firstName": "Jose",
    "lastName": "Maria",
    "birthdayDate": "January 31",
    "giftIdea": "Ring",
    "favoriteSnack": "Chips",
    "throwParty": true,
    "spotlight": true,
    "descriptionOfDreamDay": "This would be a description of a dream day",
    "avatarPicture": "picture.jpg"
    }
###
PUT http://localhost:8080/friends/629169ceaba29cb39935f614 HTTP/1.1 
content-type: application/json

{
    "firstName": "Jose",
    "lastName": "Maria",
    "birthdayDate": "January 31",
    "giftIdea": "Ring",
    "favoriteSnack": "Cake",
    "throwParty": true,
    "spotlight": true,
    "descriptionOfDreamDay": "This would be a description of a dream day",
    "avatarPicture": "picture.jpg"
    }
###
DELETE http://localhost:8080/friends/62916acf234c36527cdcb0d5 HTTP/1.1



############################
### PRODUCTION ###
############################

GET https://upcoming-birthdays.herokuapp.com/friends
###
GET https://upcoming-birthdays.herokuapp.com/friends/6287e7be2e19d620aff1fbc7
###
POST https://upcoming-birthdays.herokuapp.com/friends/ HTTP/1.1 
content-type: application/json

{
    "firstName": "Juan",
    "lastName": "Gonzalez",
    "birthdayDate": "January 31",
    "giftIdea": "Ring",
    "favoriteSnack": "Poptarts",
    "throwParty": true,
    "spotlight": true,
    "descriptionOfDreamDay": "This would be a description of a dream day",
    "avatarPicture": "picture.jpg"
    }
###
PUT https://upcoming-birthdays.herokuapp.com/friends/ HTTP/1.1 
content-type: application/json

{
    "firstName": "Juan",
    "lastName": "Gonzalez",
    "birthdayDate": "January 31",
    "giftIdea": "Ring",
    "favoriteSnack": "Veggies",
    "throwParty": true,
    "spotlight": true,
    "descriptionOfDreamDay": "This would be a description of a dream day",
    "avatarPicture": "picture.jpg"
    }
###
DELETE https://upcoming-birthdays.herokuapp.com/friends/62916a85aba29cb39935f616 HTTP/1.1